# Generated by Django 4.1.2 on 2022-10-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Family', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relative',
            name='birthdate',
            field=models.DateField(),
        ),
    ]
